mongodb = "mongodb://localhost:27017"
mongodb_db = "render"
mongodb_user = "root"
mongodb_password = "1q2w3e"


ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_MINUTES = 600
RESET_TOKEN_EXPIRE_MINUTES = 10
SECRET_KEY = "c4a1d9c51e22e3ac8c452cb3d72915c35b9be6fea9152872010d56fd95688f70"